name: ABAP_702

on:
  push:
    branches: ["702"]

permissions:
  contents: read

jobs:
  ABAP_702:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 702
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - run: npm run downport
    - name: send to downport repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: abap2UI5-downports/layout-variant-management
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: main
        publish_dir: ./downport
        deploy_key: ${{ secrets.ACTIONS_DOWNPORT_DEPLOY_KEY }}
        destination_dir: src
