name: renaming

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: rename_test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rename_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run rename
